language: r

addons:
  apt:
    packages:
      - ghostscript
      - texlive-font-utils

sudo: required

services:
  - docker

before_install:
  - docker run --rm -d -it -v $(pwd):/tmp -w /tmp --name alpine_gnuplot alpine
  - docker exec alpine_gnuplot apk add --update gnuplot
  - sudo sh -c 'echo "#!/bin/sh" > /usr/bin/gnuplot'
  - sudo sh -c
    'echo "docker exec alpine_gnuplot gnuplot \"\$@\"" >> /usr/bin/gnuplot'
  - sudo chmod +x /usr/bin/gnuplot
  - gnuplot --version

# Dummy command needed for R
install:
  - echo

script:
  # Create input for LOESS
  - ./XCSP3.plt
  # Locally Estimated Scatterplot Smoothing
  - ./LOESS.R
  # Replot using LOESS output
  - ./XCSP3.plt
  # Produce a PDF file too
  - epstopdf XCSP3.eps

after_success:
  # Decrypt private key for accessing web server
  - openssl aes-256-cbc -K $encrypted_f62db7f38058_key
    -iv $encrypted_f62db7f38058_iv
    -in key_for_uploading.pem.enc
    -out key_for_uploading.pem -d
  - chmod 600 key_for_uploading.pem
  # Upload to web server
  - scp -i key_for_uploading.pem -o StrictHostKeyChecking=no
    XCSP3.{eps,pdf,tex} pothitos@linux19.di.uoa.gr:public_html/papers/ACvsBC
  - ssh -i key_for_uploading.pem pothitos@linux19.di.uoa.gr
    chmod o+r public_html/papers/ACvsBC/XCSP3.{eps,pdf,tex}
