language: r

sudo: required

services:
  - docker

before_install:
  - docker run --rm -d -it -v $(pwd):/tmp -w /tmp --name alpine_gnuplot alpine
  - docker exec alpine_gnuplot apk add --update gnuplot
  - sudo sh -c 'echo "#!/bin/sh" > /usr/bin/gnuplot'
  - sudo sh -c
    'echo "docker exec alpine_gnuplot gnuplot \"\$@\"" >> /usr/bin/gnuplot'
  - sudo chmod +x /usr/bin/gnuplot
  - gnuplot --version

# Dummy command needed for R
install:
  - echo

script:
  - ./XCSP3.plt
  - ./LOESS.R
  - ./XCSP3.plt
